import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const ARCODEX_EXPERIMENTAL = truthy("ARCODEX_EXPERIMENTAL")
const copy = process.env["ARCODEX_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  ARCODEX_AUTO_HEAP_SNAPSHOT: truthy("ARCODEX_AUTO_HEAP_SNAPSHOT"),
  ARCODEX_GIT_BASH_PATH: process.env["ARCODEX_GIT_BASH_PATH"],
  ARCODEX_CONFIG: process.env["ARCODEX_CONFIG"],
  ARCODEX_CONFIG_CONTENT: process.env["ARCODEX_CONFIG_CONTENT"],
  ARCODEX_DISABLE_AUTOUPDATE: truthy("ARCODEX_DISABLE_AUTOUPDATE"),
  ARCODEX_ALWAYS_NOTIFY_UPDATE: truthy("ARCODEX_ALWAYS_NOTIFY_UPDATE"),
  ARCODEX_DISABLE_PRUNE: truthy("ARCODEX_DISABLE_PRUNE"),
  ARCODEX_DISABLE_TERMINAL_TITLE: truthy("ARCODEX_DISABLE_TERMINAL_TITLE"),
  ARCODEX_SHOW_TTFD: truthy("ARCODEX_SHOW_TTFD"),
  ARCODEX_PERMISSION: process.env["ARCODEX_PERMISSION"],
  ARCODEX_DISABLE_DEFAULT_PLUGINS: truthy("ARCODEX_DISABLE_DEFAULT_PLUGINS"),
  ARCODEX_DISABLE_AUTOCOMPACT: truthy("ARCODEX_DISABLE_AUTOCOMPACT"),
  ARCODEX_DISABLE_MODELS_FETCH: truthy("ARCODEX_DISABLE_MODELS_FETCH"),
  ARCODEX_DISABLE_MOUSE: truthy("ARCODEX_DISABLE_MOUSE"),
  ARCODEX_FAKE_VCS: process.env["ARCODEX_FAKE_VCS"],
  ARCODEX_SERVER_PASSWORD: process.env["ARCODEX_SERVER_PASSWORD"],
  ARCODEX_SERVER_USERNAME: process.env["ARCODEX_SERVER_USERNAME"],
  ARCODEX_ENABLE_QUESTION_TOOL: truthy("ARCODEX_ENABLE_QUESTION_TOOL"),

  // Experimental
  ARCODEX_EXPERIMENTAL,
  ARCODEX_EXPERIMENTAL_FILEWATCHER: Config.boolean("ARCODEX_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ARCODEX_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("ARCODEX_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  ARCODEX_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("ARCODEX_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  ARCODEX_MODELS_URL: process.env["ARCODEX_MODELS_URL"],
  ARCODEX_MODELS_PATH: process.env["ARCODEX_MODELS_PATH"],
  ARCODEX_DB: process.env["ARCODEX_DB"],

  ARCODEX_WORKSPACE_ID: process.env["ARCODEX_WORKSPACE_ID"],
  ARCODEX_EXPERIMENTAL_WORKSPACES: ARCODEX_EXPERIMENTAL || truthy("ARCODEX_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get ARCODEX_DISABLE_PROJECT_CONFIG() {
    return truthy("ARCODEX_DISABLE_PROJECT_CONFIG")
  },
  get ARCODEX_TUI_CONFIG() {
    return process.env["ARCODEX_TUI_CONFIG"]
  },
  get ARCODEX_CONFIG_DIR() {
    return process.env["ARCODEX_CONFIG_DIR"]
  },
  get ARCODEX_PURE() {
    return truthy("ARCODEX_PURE")
  },
  get ARCODEX_PLUGIN_META_FILE() {
    return process.env["ARCODEX_PLUGIN_META_FILE"]
  },
  get ARCODEX_CLIENT() {
    return process.env["ARCODEX_CLIENT"] ?? "cli"
  },
}
